Garden/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("Gaarden/",include("apps.mainapp.urls",namespace="main"),name="main"),
    path("Gaarden/introduction/",include("apps.introduction.urls",namespace="introduction"),name="introduction"),
    path("Gaarden/blog/",include("apps.blogApp.urls",namespace="blog"),name="blog")
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/blogApp/urls.py
from django.urls import path, re_path
from .views import *

app_name = "blog"

urlpatterns = [
    path("",show_articles,name="blog_show"),
    path("<str:slug>/",show_blog_detils,name="blog_details"),
    path('articlepdf/<int:article_id>/',show_article_pdf,name="article_pdf")
    
]

apps/introduction/urls.py
from django.urls import path
from .views import (create_message,show_message,delete_message,Update_message,
show_list_Place,show_garden_history,show_garden_part,download_path_garden,show_part_detail)

app_name="introduction"
urlpatterns = [
    path("create_message/",create_message.as_view(),name="create_message"),
    path('show_list_massege/',show_message.as_view(),name="show_list_massege"),
    path('delete_message/<int:pk>/',delete_message.as_view(),name="delete_message"),
    path('Update_message/<int:pk>/',Update_message.as_view(),name="Update_message"),
    path('garden_history/',show_garden_history,name="garden_history"),
    path('show_list_Place/',show_list_Place,name="show_Place"),
    path('show_garden_part/',show_garden_part,name="show_garden_part"),
    path('show_garden_part/<int:id>/',show_part_detail,name="show_part_detail"),
    path('download_path_garden/',download_path_garden,name="download_path_garden")
]

templates/partials/footer.html
<footer>
    تماس با ما به ادرس ایمیل :masudkolp82@gmail.com
</footer>

templates/partials/header.html
<header>
    <h1 style="font-size:60px;text-align:right;">باغ فردوس</h1>
</header>

templates/partials/navbar.html
<div class="menu__bar">
    <h1 class="logo">باغ <span>فردوس</span></h1>
    <ul>
      <li><a>صحفه اصلی</a></li>
      <li><a>معرفی باغ</a>
      <div class="dropdown__menu">
        <ul>
          <li><a href="{% url "introduction:garden_history" %}"><i>تاریخچه</i></a></li>
          <li><a href="{% url "introduction:show_garden_part" %}"><i>بخش های باغ</i></a></li>
          <li><a href="{% url "introduction:download_path_garden" %}" ><i>مسیر بازدید</i></a></li>
          <li><a href="{% url "introduction:show_Place" %}" ><i>برنامه و قوانین باغ</i></a></li>
        </ul>
      </div>
      </li>
      <li><a>گالری</a></li>
      <li><a>اموزش و پژوهش</a>
        <div class="dropdown__menu">
          <ul>
            <li><a href="{% url "blog:blog_show" %}"><i>مقالات</i></a></li>
            <li><a href="#"><i>کارگاه ها</i></a></li>
          </ul>
        </div> 
      </li>
      <li><a href="{% url "introduction:create_message" %}">تماس با ما</a></li>
    </ul>
    
    </div>
    <p style="font: size 60px;text-align: right;">
        به باغ فردوس خوش آمدید
    </p>