Garden/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("Gaarden/",include("apps.mainapp.urls",namespace="main"),name="main"),
    path("Gaarden/introduction/",include("apps.introduction.urls",namespace="introduction"),name="introduction"),
    path("Gaarden/blog/",include("apps.blogApp.urls",namespace="blog"),name="blog")
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/introduction/urls.py
from django.urls import path
from .views import (create_message,show_message,delete_message,Update_message,
show_list_Place,show_garden_history,show_garden_part,download_path_garden,show_part_detail)

app_name="introduction"
urlpatterns = [
    path("create_message/",create_message.as_view(),name="create_message"),
    path('show_list_massege/',show_message.as_view(),name="show_list_massege"),
    path('delete_message/<int:pk>/',delete_message.as_view(),name="delete_message"),
    path('Update_message/<int:pk>/',Update_message.as_view(),name="Update_message"),
    path('garden_history/',show_garden_history,name="garden_history"),
    path('show_list_Place/',show_list_Place,name="show_Place"),
    path('show_garden_part/',show_garden_part,name="show_garden_part"),
    path('show_garden_part/<int:id>/',show_part_detail,name="show_part_detail"),
    path('download_path_garden/',download_path_garden,name="download_path_garden")
]

apps/introduction/models.py
from django.db import models
from django.utils import timezone

class Visitor_Group(models.Model):
    Group_title=models.CharField(max_length=50,verbose_name="عنوان گروه")
    
    def __str__(self):
        return f'{self.Group_title}'
     
    class Meta:
        verbose_name="بازدید کننده"
        verbose_name_plural="بازدید کننده ها"
        db_table="t_Visitor_Group"
     
    
class Place(models.Model):
    place_title=models.CharField(max_length=50,verbose_name="عنوان مکان")
    Origina_photo=models.ImageField(upload_to="images/garden",verbose_name='عکس اصلی')
    Time_Visit=models.DateTimeField(default=timezone.now,verbose_name='ساعت بازدید')
    Description=models.TextField(verbose_name='اطلاعات بیشتر')
    Rules=models.CharField(max_length=200,verbose_name='قوانین')
    def __str__(self):
        return f'{self.place_title}'
     
    class Meta:
        verbose_name="مکان"
        verbose_name_plural="مکان ها"
        db_table="t_Place"
     
    
    
class Ticket_Price(models.Model):
     group_visit=models.ForeignKey(Visitor_Group,on_delete=models.CASCADE,verbose_name='گروه بازدید')
     place_visit=models.ForeignKey(Place,on_delete=models.CASCADE,verbose_name="مکان بازدید")
     Ticket_price=models.IntegerField(verbose_name=" بهای بلیط")
     
     def __str__(self):
         return f'{self.group_visit}\t{self.place_visit}\t{self.Ticket_price}'
     
     class Meta:
        verbose_name="قیمت بلیط"
        verbose_name_plural="قیمت بلیط ها"
        db_table="t_Ticket_Price"
     
class Message(models.Model):
    name=models.CharField(max_length=50,verbose_name="نام")
    family=models.CharField(max_length=50,verbose_name="نام خانوادگی")
    email=models.EmailField(max_length=254,verbose_name="ایمیل")
    title_message=models.CharField(max_length=60,verbose_name="موضوع پیام")
    text_message=models.TextField(verbose_name="متن پیام")
    Time_message=models.DateTimeField(default=timezone.now,verbose_name='تاریخ ثبت پیام')
    show_message=models.BooleanField(verbose_name="دیده شده/دیده نشده",default=False)
    def __str__(self):
        return f'{self.name}\t{self.family}\t{self.email}\t{self.title_message}\t{self.Time_message}\t{self.show_message}'
     
    class Meta:
        verbose_name="پیام"
        verbose_name_plural="پیام ها"
        db_table="t_Message"
    
    

apps/introduction/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView,DeleteView,UpdateView
from django.views.generic import ListView
from .models import Message,Ticket_Price,Visitor_Group,Place
from django.urls import reverse
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponse,HttpResponseNotFound

class create_message(CreateView):
    model=Message
    fields=["name","family","email","title_message","text_message"]
    template_name="introduction/create_message.html"
    context_object_name="form"
    def get_success_url(self):
        return reverse("show_list_massege")

class show_message(ListView):
    model=Message
    template_name="introduction/list_massege.html"
    context_object_name="lists"
    
    
class delete_message(DeleteView):
    model=Message
    template_name="introduction/delete_message.html"
    fields="__all__"
    context_object_name="object"
    def get_success_url(self):
        return reverse("show_list_massege")
    
class Update_message(UpdateView):
    model=Message
    template_name="introduction/Update_message.html"
    fields=["name","family","text_message"]
    context_object_name="form"
    def get_success_url(self):
        return reverse("show_list_massege")
    
#=================================================================================
#  تاریجچه باغ 

def show_garden_history(request):
    return render(request,"introduction/show_garden_history.html")
 
#=============================================================
#برنامه و قوانین باغ


    
def show_list_Place(request):
    place=Place.objects.all()
    ticket_price=Ticket_Price.objects.all()
    
    context={
        "Places":place,
        "Ticket_Prices":ticket_price

    }

    return render(request,"introduction/show_list_Place.html",context)
#=====================================================================
#بخش های باغ 

def show_garden_part(request):
    place=Place.objects.all()
    context={
        "Places":place
    }

    return render(request,"introduction/show_garden_part.html",context)
#=====================================================================
#جزییات بخش ها

def show_part_detail(request,id):
    place=Place.objects.get(id=id)
    return render(request,"introduction/part_detail.html",{"place":place})
#=====================================================================
# مسیر بازدید

def download_path_garden(request):
    fs=FileSystemStorage()
    fie_name="pdf/ferdowsGardenPath.pdf"
    if fs.exists(fie_name):
        with fs.open(fie_name) as pdf:
            response=HttpResponse(pdf,content_type='application/pdf')
            response["Content-Disposition"]="attachment; filename=ferdowsGardenPath.pdf"
            return response
    else:
        return HttpResponseNotFound("File not found.....")
            

templates/introduction/Update_message.html
{% extends "maintemplate.html" %}
{% block content %}
    <h1>اپدیت پیام</h1>
    <form method="post",enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="اپدیت  پیام">
    </form>
{% endblock content %}

templates/introduction/create_message.html
{% extends "maintemplate.html" %}
{% block content %}
    <h1>فرم ارسال پیام</h1>
    <form method="post",enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="ارسال پیام">
    </form>
{% endblock content %}

templates/introduction/delete_message.html
{% block content %}
    <form method="post">
        {% csrf_token %}
        <h3>ایا میخواهید پست
            <span style="color:red;">
            {{object.title_message}}
            </span>
            را حذف کنید؟</h3>
        <input type="submit" value="بله">
    </form>
{% endblock content %}

templates/introduction/list_massege.html
{% extends "maintemplate.html" %}
{% block content %}


<h1>لیست پیام ها</h1>

<table>
    <tr>
        <th>نام</th>
        <th>نام خانوادگی</th>
        <th>ایمیل</th>
        <th>موضوع پیام</th>
        <th>متن پیام</th>
        <th>تاریخ ثبت نام</th>
        <th>دیده شده /دیده نشده</th>
    </tr>
    {% for list in lists %}
        <tr>
            <td>{{list.name}}</td>
            <td>{{list.family}}</td>
            <td>{{list.email}}</td>
            <td>{{list.title_message}}</td>
            <td>{{list.text_message}}</td>
            <td>{{list.Time_message}}</td>
            <td>{{listshow_message.}}</td>

        </tr>
    
    {% endfor %}



</table>
{% endblock content %}

templates/introduction/part_detail.html
{% extends "maintemplate.html" %}

{% block content %}
    <h1>{{place.place_title}}</h1>
    <img src="{{media_url}}{{place.Origina_photo}}" class="img_300x200" >
    <p>{{place.Description}}</p>
{% endblock %}

templates/introduction/show_garden_history.html
{% extends "maintemplate.html" %}

{% block content %}
<div>
    <img src="{{media_url}}images/garden/history.jpg">
</div>
<p>
    تاریخچه تاریخچه تاریخچه تاریخچه تاریخچه تاریخچه تاریخچه تاریخچه تاریخچه تاریخچه تاریخچه تاریخچه
    تاریخچه تاریخچه تاریخچه تاریخچه تاریخچه تاریخچه تاریخچه تاریخچه تاریخچه تاریخچه تاریخچه تاریخچه
    تاریخچه تاریخچه تاریخچه تاریخچه تاریخچه تاریخچه تاریخچه تاریخچه تاریخچه تاریخچه تاریخچه تاریخچه
    تاریخچه تاریخچه تاریخچه تاریخچه تاریخچه تاریخچه تاریخچه تاریخچه تاریخچه تاریخچه تاریخچه تاریخچه
</p>
{% endblock %}

templates/introduction/show_garden_part.html
{% extends "maintemplate.html" %}

{% block content %}
<h1>بخش های باغ فردوس</h1>
{% for place in Places %}
      
    <div class="row">
        <img src="{{media_url}}{{place.Origina_photo}}" class="img_300x200" >
    
        <div class = "col-sm-6 col-md-4 col-lg-4">
            <h3>{{ place.place_title }}</h3>
            <p class="description">{{ place.Description }}</p>
            <p><a href="{% url "introduction:show_part_detail" id=place.id %}" class="btn btn-primary btn-block" role="button">مشاهده جزِیات</a></p>

        </div>
    </div>
    


{% endfor %}

{% endblock content %}

templates/introduction/show_list_Place.html
{% extends "maintemplate.html" %}
{% block content %}


<h1>روز های بازدید</h1>

    <ul>
    {% for place in Places %}
        
        <li>
            <h3>روز و ساعت  بازدید <strong>{{place.place_title}}</strong>:{{place.Time_Visit}}</h3>
            
           

        <td>{{place.place_title}}</td>
        <td>{{place.Time_Visit}}</td>
        <td>{{place.Description}}</td>
        <td>{{place.Rules}}</td>
        <td><img src="{{media_url}}{{place.Origina_photo}}" alt="{{place.place_title}}"></td>


        </tr>

    {% endfor %}
    </ul>
    <ul>
    {% for Ticket_Price in Ticket_Prices %}
        <li>بهای بلیط {{Ticket_Price.place_visit}}</li>برای بازید کننده  
        {{Ticket_Price.group_visit}}:{{Ticket_Price.Ticket_price}}
        </li>
    {% endfor %}
    </ul>
{% endblock %}