Garden/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("Gaarden/",include("apps.mainapp.urls",namespace="main"),name="main"),
    path("Gaarden/introduction/",include("apps.introduction.urls",namespace="introduction"),name="introduction"),
    path("Gaarden/blog/",include("apps.blogApp.urls",namespace="blog"),name="blog")
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/blogApp/urls.py
from django.urls import path, re_path
from .views import *

app_name = "blog"

urlpatterns = [
    path("",show_articles,name="blog_show"),
    path("<str:slug>/",show_blog_detils,name="blog_details"),
    path('articlepdf/<int:article_id>/',show_article_pdf,name="article_pdf")
    
]

templates/articles_app/blog.html
{% extends "maintemplate.html" %}

{% block title %}مقاله ها{% endblock title %}

{% block content %}
    <main class="">
    <h1 style="text-align:center;">مقاله ها</h1>  
    <hr>
    {% for article in articles %}
        {% if article.is_active == True %}
            <section>
                <section>
                    <h3>{{ article.title }}</h3>
                    <br>
                    <p>{{ article.short_text }}</p>
                    <br>
                    {% for i in articles_authors %}
                        {% if i.article_id == article.id %}
                            {% for author in authors %}
                                {% if author.id == i.author_id %}
                                    <span>{{author.name}} {{author.family}} &nbsp;&nbsp;&nbsp; </span>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                    {% endfor %}
                
                <div>
                    <i class="fa fa-list-alt"></i> <span>{{article.group}}</span>
                    <br>
                    <i class="fa fa-calendar"></i> <span>{{article.update_date}}</span> |
                    <br>
                    <i class="fa fa-eye"></i> <span>{{article.view_number}}</span> |
                    <br>
                    <a href="/Gaarden/blog/{{article.slug}}/">مشاهده مقاله</a>
                </div>
                </section>
                <section>
                    <img src="{{ media_url }}images/blog/{{ article.image_name }}" alt="تصویر اصلی مقاله" class="img_300x200">
                </section>
            </section>
            <hr>
        </main>
        {% endif %}
    {% endfor %}
{% endblock content %}

templates/articles_app/blog_details.html
{% extends "maintemplate.html" %}

{% block title %}مقاله{% endblock title %}

{% block content %}
    <main class="article-main">
        <section>
            <h4>گروه مقاله : {{article.group}}</h4>
            <span>نویسندگان : </span>
            {% for author in authors %}
            {% if author.id == article.author_id %}
                <span style="font-size:14px;">{{author.name}} {{author.family}} &nbsp;&nbsp;&nbsp;</span>
            {% endif %}
        {% endfor %}
        
        
        <h4>چکیده</h4>
        <p>{{article.short_text}}</p>

        <h4>واژگان کلیدی</h4>
        <p>{{article.key_words}}</p>

        <h4>تعداد بازدید : {{article.view_number}}</h4>


        <h4>متن مقاله</h4>
        <p>{{article.text}}</p>

        <i class="glyphicon glyphicon-download-alt download-icon"></i>
        <a href="{% url "blog:article_pdf" article.id %}">دانلود متن مقاله</a>
        {% comment %} <a href="{{media_url}}pdf/blog/articlepdf/{{article.pdf_file_name}}">دانلود متن مقاله</a> {% endcomment %}
        </section>
            <h4>تصاویر مرتبط با مقاله</h4>
        {% for image in image_List %}
            <a target="_blank" href="{{media_url}}images/blog/articles_{{article.id}}/{{image}}"></a>
            <img src="{{media_url}}images/blog/articles_{{article.id}}/{{image}}" alt="تصویر مقاله" class="img_300x200">
        {% endfor %} 
            
    </main>


{% endblock content %}